# Config file for automatic testing at travis-ci.com

language: python

python:
   - 3.8
   - 3.7
   - 3.6
   - 3.5
  
cache:
   - pip

install:
   - pip install -U tox-travis

# Command to run tests.
script:
   - tox

# Go to travis-ci.org, and look at settings, under the project in the dashboard.
# Add the project-specific token as an environment variable
# ($PYPI_PARSER201_TOKEN). This will allow travis to automatically deploy to
# pypi if the build is successful.

# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: __token__
#   password: $PYPI_PARSER201_TOKEN
#   on:
#     tags: true
#     repo: geozeke/parser201
#     python: 3.8
